version: '3.9'

services:
  flask_app:
    build: ./api
    container_name: reposteria_flask
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=reposteria
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      - postgres_db
    restart: always

  nginx:
    image: nginx:latest
    container_name: reposteria_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app
    restart: always

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reposteria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
